version: '3'

services:
  ##
  ## CONTAINER for PostgreSQL database
  ## database access URL:
  ##     postgres://POSTGRES_USER:POSTGRES_PASSWORD@localhost:HOST_PORT/POSTGRES_DB
  ## ----------------------------------------
  database:
    image: postgres:latest
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: dockerpguser
      POSTGRES_PASSWORD: t3st3r0fThings!
      POSTGRES_DB: challenge_solution
      POSTGRES_HOST: localhost
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
  ##
  ## CONTAINER for Server Application
  ## to test service run:
  ##     docker-compose up --build -d server
  ## ----------------------------------------
  server:
    build:
      context: ./server
    ports:
      - 8080:8080 # expose ports - HOST:CONTAINER
    environment:
      PORT_DB: 5432
      POSTGRES_USER: dockerpguser
      POSTGRES_PASSWORD: t3st3r0fThings!
      POSTGRES_DB: challenge_solution
      POSTGRES_HOST: database
    volumes:
      - './server:/app/server'
      - '/app/server/node_modules'
    depends_on:
      - database
    command: npm run server:dev
  ##
  ## CONTAINER for Client Side Application
  ## to test service run:
  ##     docker-compose up --build -d client
  ## ----------------------------------------
  client:
    stdin_open: true
    build:
      context: ./client
    ports:
      - 3000:3000 # expose ports - HOST:CONTAINER (for create-react-app)
      - 35729:35729 # expose ports - HOST:CONTAINER (for serviceworker warm reloading)
    volumes:
      - './client:/app/client'
      - '/app/client/node_modules'
    depends_on:
      - server
    command: npm run start
